default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root
  password: newlife4829
  host: 127.0.0.1
  port: 3406

development:
  <<: *default
  database: manspouch

test:
  <<: *default
  database: manspouch

production:
  <<: *default
  database: manspouch
