default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

  host: manspouchtest.crq3wu1eydju.ap-northeast-2.rds.amazonaws.com
  port: 3306
  encoding: utf8
  username: root
  password: manspouch1234
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: manspouchtest

test:
  <<: *default
  database: manspouchtest

production:
  <<: *default
  database: manspouchtest
  username: root
  password: manspouch1234